// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QLNH_Backend.DAL;

#nullable disable

namespace QLNH.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812192344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QLNH_Backend.Models.BanAn", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBan"));

                    b.Property<int>("SoGhe")
                        .HasColumnType("integer");

                    b.Property<int>("Tang")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Trống");

                    b.HasKey("MaBan");

                    b.ToTable("BanAns");

                    b.HasData(
                        new
                        {
                            MaBan = 101,
                            SoGhe = 2,
                            Tang = 1,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 102,
                            SoGhe = 2,
                            Tang = 1,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 103,
                            SoGhe = 4,
                            Tang = 1,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 104,
                            SoGhe = 4,
                            Tang = 1,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 204,
                            SoGhe = 4,
                            Tang = 2,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 205,
                            SoGhe = 8,
                            Tang = 2,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 206,
                            SoGhe = 8,
                            Tang = 2,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = 207,
                            SoGhe = 12,
                            Tang = 2,
                            TrangThai = "Trống"
                        });
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("integer");

                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ThoiGianGoi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaHoaDon", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietPhieuGoi", b =>
                {
                    b.Property<int>("MaPhieu")
                        .HasColumnType("integer");

                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Chờ xử lý");

                    b.HasKey("MaPhieu", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietPhieuGois");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("integer");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("integer");

                    b.HasKey("MaPhieuNhap", "MaNguyenLieu");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongXuat")
                        .HasColumnType("integer");

                    b.HasKey("MaPhieuXuat", "MaNguyenLieu");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QLNH_Backend.Models.DinhLuong", b =>
                {
                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("integer");

                    b.Property<double>("SoLuongDung")
                        .HasColumnType("double precision");

                    b.HasKey("MaMon", "MaNguyenLieu");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("DinhLuongs");
                });

            modelBuilder.Entity("QLNH_Backend.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("numeric");

                    b.Property<int>("MaKh")
                        .HasColumnType("integer");

                    b.Property<int>("MaNv")
                        .HasColumnType("integer");

                    b.Property<string>("PhuongThucTt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Tiền mặt");

                    b.Property<DateTime>("ThoiGianRa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ThoiGianVao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TienKhachDua")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TienThua")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Vat")
                        .HasColumnType("numeric");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QLNH_Backend.Models.HoaDonBan", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("integer");

                    b.Property<int>("MaBan")
                        .HasColumnType("integer");

                    b.HasKey("MaHoaDon", "MaBan");

                    b.HasIndex("MaBan");

                    b.ToTable("HoaDonBans");
                });

            modelBuilder.Entity("QLNH_Backend.Models.KhachHang", b =>
                {
                    b.Property<int?>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("MaKh"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("integer");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("text");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QLNH_Backend.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMon"));

                    b.Property<bool>("DangKinhDoanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("numeric");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<int>("MaNhom")
                        .HasColumnType("integer");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaNhom");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("QLNH_Backend.Models.NguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("text");

                    b.Property<double>("SoLuongTon")
                        .HasColumnType("double precision");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaNguyenLieu");

                    b.ToTable("NguyenLieus");
                });

            modelBuilder.Entity("QLNH_Backend.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNv"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThaiHoatDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaNv");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaNv = 1,
                            HoTen = "Phục Vụ 1",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "pv1",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Phục vụ"
                        },
                        new
                        {
                            MaNv = 2,
                            HoTen = "Phục Vụ 2",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "pv2",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Phục vụ"
                        },
                        new
                        {
                            MaNv = 3,
                            HoTen = "Phục Vụ 3",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "pv3",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Phục vụ"
                        },
                        new
                        {
                            MaNv = 4,
                            HoTen = "Phục Vụ 4",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "pv4",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Phục vụ"
                        },
                        new
                        {
                            MaNv = 5,
                            HoTen = "Phục Vụ 5",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "pv5",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Phục vụ"
                        },
                        new
                        {
                            MaNv = 6,
                            HoTen = "Bếp 1",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "bep1",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Bếp"
                        },
                        new
                        {
                            MaNv = 7,
                            HoTen = "Bếp 2",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "bep2",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Bếp"
                        },
                        new
                        {
                            MaNv = 8,
                            HoTen = "Bếp 3",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "bep3",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Bếp"
                        },
                        new
                        {
                            MaNv = 9,
                            HoTen = "Thu Ngân 1",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "tn1",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Thu ngân"
                        },
                        new
                        {
                            MaNv = 10,
                            HoTen = "Thu Ngân 2",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "tn2",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Thu ngân"
                        },
                        new
                        {
                            MaNv = 11,
                            HoTen = "Quản Lý",
                            MatKhau = "$2a$11$oOycLqRaWyE8r.VGoAY3x.dWpSopPJ47qJqdKAOxoPMDHcNkQPhJa",
                            NgayTao = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenDangNhap = "ql1",
                            TrangThaiHoatDong = "Làm việc",
                            VaiTro = "Quản lý"
                        });
                });

            modelBuilder.Entity("QLNH_Backend.Models.NhomMon", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNhom");

                    b.ToTable("NhomMons");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuGoi", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieu"));

                    b.Property<int>("MaBan")
                        .HasColumnType("integer");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("integer");

                    b.Property<int>("MaNv")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaNv");

                    b.ToTable("PhieuGois");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<int>("MaNv")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNv");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<int>("MaNv")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("MaNv");

                    b.ToTable("PhieuXuats");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ThongBao", b =>
                {
                    b.Property<int>("MaTb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTb"));

                    b.Property<bool?>("DaXem")
                        .HasColumnType("boolean");

                    b.Property<int>("MaBan")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaTb");

                    b.HasIndex("MaBan");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("QLNH_Backend.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietPhieuGoi", b =>
                {
                    b.HasOne("QLNH_Backend.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietPhieuGois")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.PhieuGoi", "MaPhieuNavigation")
                        .WithMany("ChiTietPhieuGois")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QLNH_Backend.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.PhieuNhap", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("MaPhieuNhapNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QLNH_Backend.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.PhieuXuat", "MaPhieuXuatNavigation")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("MaPhieuXuatNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.DinhLuong", b =>
                {
                    b.HasOne("QLNH_Backend.Models.MonAn", "MaMonNavigation")
                        .WithMany("DinhLuongs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("DinhLuongs")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaNguyenLieuNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.HoaDon", b =>
                {
                    b.HasOne("QLNH_Backend.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.HoaDonBan", b =>
                {
                    b.HasOne("QLNH_Backend.Models.BanAn", "MaBanNavigation")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.MonAn", b =>
                {
                    b.HasOne("QLNH_Backend.Models.NhomMon", "MaNhomNavigation")
                        .WithMany("MonAns")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("MaNhomNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuGoi", b =>
                {
                    b.HasOne("QLNH_Backend.Models.BanAn", "MaBanNavigation")
                        .WithMany("PhieuGois")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("PhieuGois")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNH_Backend.Models.NhanVien", "MaNvNavigation")
                        .WithMany("PhieuGois")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuNhap", b =>
                {
                    b.HasOne("QLNH_Backend.Models.NhanVien", "MaNvNavigation")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuXuat", b =>
                {
                    b.HasOne("QLNH_Backend.Models.NhanVien", "MaNvNavigation")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.ThongBao", b =>
                {
                    b.HasOne("QLNH_Backend.Models.BanAn", "MaBanNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("MaBanNavigation");
                });

            modelBuilder.Entity("QLNH_Backend.Models.BanAn", b =>
                {
                    b.Navigation("HoaDonBans");

                    b.Navigation("PhieuGois");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QLNH_Backend.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("HoaDonBans");

                    b.Navigation("PhieuGois");
                });

            modelBuilder.Entity("QLNH_Backend.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QLNH_Backend.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ChiTietPhieuGois");

                    b.Navigation("DinhLuongs");
                });

            modelBuilder.Entity("QLNH_Backend.Models.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("ChiTietPhieuXuats");

                    b.Navigation("DinhLuongs");
                });

            modelBuilder.Entity("QLNH_Backend.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhieuGois");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("QLNH_Backend.Models.NhomMon", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuGoi", b =>
                {
                    b.Navigation("ChiTietPhieuGois");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QLNH_Backend.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });
#pragma warning restore 612, 618
        }
    }
}
